sudo: required
language: node_js
node_js: '12'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH ;
script:
- yarn
before_deploy:
- printf "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}\n" >> ~/.npmrc
deploy:
  provider: script
  script: yarn run publish:next
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: bhMaDI9JuD5JarnIoG86lhEdtvI6Rk+CbNWZ7/vW9CZXp03Sw1sOCtmDvNEXsqO+nNsoRg/j7rZvEO8l7S4Pdh15O4v7RAb9av+j9IJ64ZUSynknYJCwatIkiXz8O7+Lt3vYWGJm0YwEv76IYPa/9cGq9BMVW5lsnS2pjmW6CWWgUaqdZsaNYUUoYzv/SBAyqXVKOii0mzUnemeGSB/DKXv/xePf8XMNnChwAUdH3sdaH3J7PBIMV4mfEtpdbTMGWT87LmA90EDTm0M2wJKndY1PvDTir7o7F4pd50qZE59fHM4FPpx+xENRAoGan5+6xbiG3NyoR3DKQNm4Sl6PBXdYoei1nBCX8wXI/r8o20W6MIjsSPfz4RQq1hsGPfH83WftfviDNKciArLVE1w+9oFsrw2tuZApmWMdaJN5NxswfpJFQ2EGA50qVd5bpYqAhUqIK5wwoOt3Mw5sioJBP0FLfmbM4EBF9Y0t+zXUWbMhJmASoB1zK0Cod2lvs3QWHHaW3okWIPkRkoW012Aw7I3s4ssaki0UtOMEpFsMkkCtJ4yz+ZT/QRJymDCWqEn9uHpkFJkCU3lkeTgq5qOUr11UcrMMfumRD4HSsHe6eRJy6rm2CV5o/qypkwHM88voaUN/nHMc5l2N2eKh0JprKkCKt1QvPgpJyMzACDCAHZI=
